### ISSUE TITLE
How to run in Rust

### ISSUE THREAD

**Issue by TheCloudlet** [songzhi/c_lexer#1]
When I clone the directory and run "cargo run"
it gives me a "a bin target must be available for `cargo run`"

what can I do?

**Comment by songzhi** [comment]
It's a library, you need add it as a dependency in your project's `Cargo.toml`.  [see this](https://doc.rust-lang.org/cargo/guide/project-layout.html)

**Comment by TheCloudlet** [comment]
I'm interested in Implement your library and fork it into a full RISK-V C compiler as my Rust learning project.
Can you give me some clues where to start from?

**Comment by songzhi** [comment]
Actually it's a copy of [this](https://github.com/hrvolapeter/javascript-lexer) for C language. [Here's](https://medium.com/@retep007/javascript-lexing-for-high-performance-f9a800ec930d) the article about the original project.

**Comment by songzhi** [comment]
Actually this project is a copy of [this](https://github.com/hrvolapeter/javascript-lexer) for C language. [Here's](https://medium.com/@retep007/javascript-lexing-for-high-performance-f9a800ec930d) the post about the original project. 

For RISC-V porting, I have no experience about it. But this project doesn't use OS/Arch-specific features so I think it's easy to port.

**Comment by TheCloudlet** [comment]
Thanks a lot, I appreciate it.
Cheers mate!
